### ISSUE TITLE
Why not NativeWind?

### ISSUE THREAD

**Issue by cvolant** [Malberee/nextui-native-demo#2]
Hi,

Thanks for sharing you work. I discovered it because we are trying to do the same, but only for our specific needs.
We chose [NativeWind v4](https://www.nativewind.dev/v4/overview) and it plays quite well NextUI.

Did you consider it? If yes, I would be interested to know why you did not choose to use it...

**Comment by Malberee** [comment]
Hi. No particular reason, I just don't really like tailwind and I'm more used to styled components :)

**Comment by cvolant** [comment]
Thank you for the answer.
